# Generated by Django 5.2.3 on 2025-06-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя сотрудника",
                        max_length=50,
                        verbose_name="Имя сотрудника",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию сотрудника",
                        max_length=50,
                        verbose_name="Фамилия сотрудника",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество сотрудника",
                        max_length=50,
                        null=True,
                        verbose_name="Отчество сотрудника",
                    ),
                ),
                (
                    "post",
                    models.CharField(
                        blank=True,
                        help_text="Введите должность сотрудника",
                        max_length=100,
                        null=True,
                        verbose_name="Должность сотрудника",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите задачу",
                        max_length=100,
                        verbose_name="Наименование задачи",
                    ),
                ),
                (
                    "term",
                    models.PositiveSmallIntegerField(
                        help_text="Введите сроки исполнения задачи в днях",
                        verbose_name="Срок исполнения задачи в днях",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        help_text="Выберите статус выполнения задачи",
                        verbose_name="Статус выполнения задачи",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.employee",
                        verbose_name="Исполнитель задачи",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите задачу которую необходимо сделать перед выполнением этой",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
        ),
    ]
