# Generated by Django 5.2.3 on 2025-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.CharField(
                choices=[("completed", "Выполнена"), ("in_progress", "В процессе")],
                default="in_progress",
                help_text="Выберите статус выполнения задачи",
                verbose_name="Статус выполнения задачи",
            ),
        ),
    ]
